{% set version = "0.4.0" %}

package:
  name: riip
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - numpy
    - scipy
    - cython
    - setuptools
  run:
    - gitpython
    - matplotlib
    - numpy
    - pandas
    - pytables
    - python
    - pyyaml
    - scipy
    - ipython

test:
  imports:
    - riip

about:
  home: "https://github.com/mnishida/RII_Pandas"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python 3 + Pandas wrapper for the refractiveindex.info database"
  doc_url: https://github.com/mnishida/RII_Pandas/tree/master/tutorial

extra:
  recipe-maintainers:
    - mnishida
