from __future__ import annotations

import numpy as np

def formula_1_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_2_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_3_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_4_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_5_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_6_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_7_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_8_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_9_cython(w: complex, cs: np.ndarray) -> float: ...
def formula_21_cython(w: complex, cs: np.ndarray) -> complex: ...
def formula_22_cython(w: complex, cs: np.ndarray) -> complex: ...
