name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools Cython numpy scipy wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist
          twine upload dist/*
  deploy_conda_linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python with Conda ${{ matrix.python-version }}
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-conda: true
      - name: Install dependencies
        run: |
          conda install conda-build conda-verify anaconda-client
      - name: Build and publish
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_TOKEN }}
        run: |
          conda build --output-folder conda_pkg conda_pkg
          anaconda upload conda_pkg/linux-64/riip-*.tar.bz2
  # deploy_conda_windows:
  #   runs-on: windows-latest
  #   strategy:
  #     max-parallel: 6
  #     matrix:
  #       python-version: [3.8, 3.9]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python with Conda ${{ matrix.python-version }}
  #       uses: s-weigand/setup-conda@v1
  #       with:
  #         update-conda: true
  #         python-version: ${{ matrix.python-version }}
  #         activate-conda: true
  #     - name: Install dependencies
  #       run: |
  #         conda install conda-build conda-verify anaconda-client
  #     - name: Build and publish
  #       env:
  #         ANACONDA_API_TOKEN: ${{ secrets.CONDA_TOKEN }}
  #       run: |
  #         conda build --output-folder conda_pkg conda_pkg
  #         anaconda upload conda_pkg/win-64/riip-*.tar.bz2
